import { useQuery } from "@tanstack/react-query";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { getMetadata, getSchemaContext } from "../../lib/api";
import SchemaEditor from "./SchemaEditor";

interface SchemaModalProps {
  open: boolean;
  onClose: () => void;
  pipelineId: string;
  nodeId: string;
  readOnly?: boolean;
}

interface ColumnMeta {
  dtype?: string;
  semantic_type?: string;
  role?: string;
  nullable?: boolean;
  unique_count?: number;
  null_pct?: number;
  [key: string]: unknown;
}

interface MetadataPayload {
  columns: Record<string, ColumnMeta>;
  row_count?: number;
  generated_by?: string;
  [key: string]: unknown;
}

export default function SchemaModal({
  open,
  onClose,
  pipelineId,
  nodeId,
  readOnly,
}: SchemaModalProps) {
  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-[80vw] max-h-[80vh] overflow-auto">
        <DialogHeader>
          <DialogTitle>
            Column Schema{readOnly ? " (read-only)" : ""}
          </DialogTitle>
        </DialogHeader>
        {readOnly ? (
          <ReadOnlySchema pipelineId={pipelineId} nodeId={nodeId} open={open} />
        ) : (
          <SchemaEditor pipelineId={pipelineId} nodeId={nodeId} />
        )}
      </DialogContent>
    </Dialog>
  );
}

function ReadOnlySchema({
  pipelineId,
  nodeId,
  open,
}: {
  pipelineId: string;
  nodeId: string;
  open: boolean;
}) {
  const { data, isLoading } = useQuery({
    queryKey: ["metadata", pipelineId, nodeId],
    queryFn: async () => {
      const res = await getMetadata(pipelineId, nodeId);
      if (
        res.metadata &&
        typeof res.metadata === "object" &&
        "columns" in res.metadata
      ) {
        return res.metadata as MetadataPayload;
      }
      // Fall back to BFS upstream schema context
      const ctx = await getSchemaContext(pipelineId, nodeId);
      if (
        ctx.schema_context &&
        typeof ctx.schema_context === "object" &&
        "columns" in ctx.schema_context
      ) {
        return ctx.schema_context as MetadataPayload;
      }
      return null;
    },
    enabled: open && !!pipelineId && !!nodeId,
  });

  if (isLoading) {
    return <div style={mutedStyle}>Loading schema...</div>;
  }

  if (!data?.columns) {
    return (
      <div style={mutedStyle}>
        No schema available — run upstream nodes first
      </div>
    );
  }

  const columns = Object.entries(data.columns);

  return (
    <div style={{ fontSize: 12, fontFamily: "'Inter', sans-serif" }}>
      <table style={{ width: "100%", borderCollapse: "collapse", tableLayout: "fixed" }}>
        <thead>
          <tr style={thRowStyle}>
            <th style={{ ...thStyle, width: "30%" }}>Column</th>
            <th style={{ ...thStyle, width: "18%" }}>Dtype</th>
            <th style={{ ...thStyle, width: "22%" }}>Semantic Type</th>
            <th style={{ ...thStyle, width: "18%" }}>Role</th>
            <th style={{ ...thStyle, width: "12%" }}>Null %</th>
          </tr>
        </thead>
        <tbody>
          {columns.map(([name, col]) => (
            <tr key={name} style={trStyle}>
              <td style={{ ...tdStyle, fontWeight: 600, fontFamily: "'JetBrains Mono', monospace", fontSize: 11 }}>
                {name}
              </td>
              <td style={{ ...tdStyle, color: "var(--text-muted)" }}>{col.dtype ?? "—"}</td>
              <td style={tdStyle}>{col.semantic_type ?? "—"}</td>
              <td style={tdStyle}>{col.role ?? "—"}</td>
              <td style={tdStyle}>
                {typeof col.null_pct === "number"
                  ? `${(col.null_pct * 100).toFixed(1)}%`
                  : "—"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {data.row_count != null && (
        <div style={{ padding: "6px 16px 8px", color: "var(--text-muted)", fontSize: 10 }}>
          {data.row_count.toLocaleString()} rows
          {data.generated_by ? ` · generated by ${data.generated_by}` : ""}
        </div>
      )}
    </div>
  );
}

// ── Styles ───────────────────────────────────────────────────────

const mutedStyle: React.CSSProperties = {
  padding: "12px 16px",
  color: "var(--text-muted)",
  fontSize: 12,
  fontFamily: "'Inter', sans-serif",
  lineHeight: 1.5,
};

const thRowStyle: React.CSSProperties = {
  borderBottom: "1px solid var(--border-default)",
  color: "var(--text-muted)",
  fontSize: 10,
  fontWeight: 600,
  textTransform: "uppercase",
  letterSpacing: "0.05em",
};

const thStyle: React.CSSProperties = {
  padding: "6px 8px 6px 16px",
  textAlign: "left",
  fontWeight: 600,
};

const trStyle: React.CSSProperties = {
  borderBottom: "1px solid var(--border-default)",
};

const tdStyle: React.CSSProperties = {
  padding: "5px 8px 5px 16px",
  verticalAlign: "middle",
  fontSize: 11,
};
